;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Abilities.Attack.Weapon",NewTagName="Abilities.Attack.Enemy.Melee.SwordSlash")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Attack.Enemy",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Enemy.Melee.SwordSlash",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Enemy.Ranged",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Enemy.Ranged.BaseSpell",DevComment="")
+GameplayTagList=(Tag="Damage.Hit",DevComment="")
+GameplayTagList=(Tag="Damage.Projectile.Spell",DevComment="")
+GameplayTagList=(Tag="Damage.Stun",DevComment="")
+GameplayTagList=(Tag="Upgrades.HealthRegen",DevComment="")
+GameplayTagList=(Tag="Upgrades.ManaRegen",DevComment="")
+GameplayTagList=(Tag="Upgrades.Projectile",DevComment="")
+GameplayTagList=(Tag="Upgrades.WalkSpeed",DevComment="")

